# Generated by Django 5.1.3 on 2025-07-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ordered_at_order_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='ordered_at',
        ),
    ]
