# Generated by Django 5.1.3 on 2025-07-22 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_item_orderitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
