# Generated by Django 5.1.3 on 2025-07-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='total_amount',
        ),
    ]
