# Generated by Django 5.1.3 on 2025-07-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_timestamp_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='ordered_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
