# Generated by Django 5.1.3 on 2025-07-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_created_at_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
    ]
